import Header from '../components/Header';
import './globals.css';
import { ClerkLoaded, ClerkLoading, ClerkProvider } from '@clerk/nextjs';
import Loader from '../components/Loader';

export const metadata = {
  title: 'Next Auth App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="antialiased">
          <ClerkLoading>
            <Loader />
          </ClerkLoading>
          <ClerkLoaded>
            <Header />
            {children}
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
